import random as rd
import time


water_prompts = [
    "Time to hydrate, asshole, this is the mildest reminder you'll get.",
    "Did yo mama not teach you the importance of drinking water?",
    "Drink some fucking water, you dehydrated cretin.",
    "Your piss looks like motor oil, go refill that cup, bitch.",
    "Stop doom-scrolling and chug some H2O, dickhead.",
    "Your organs are screaming, you waterless buffoon.",
    "If you don’t drink water soon, your skin’s gonna flake off like a damn croissant.",
    "You’re one dry fart away from becoming human jerky. Hydrate, dumbass.",
    "Your brain’s so dry it’s rattling in your skull. Drink up, jackass.",
    "Even your houseplants are embarrassed for you. get some water, you absolute walnut.",
    "You’re thirstier than a simp in a titty streamer chat, go drink.",
    "Your bloodstream’s basically dust and caffeine. Fix it, shitlord.",
    "You’re not a cactus, motherfucker. Go drink something that isn’t espresso.",
    "Your kidneys just filed a restraining order. Water. Now.",
    "You look like a raisin that escaped from a nursing home. Hydrate, crusty.",
    "Jesus turned wine into water for a reason, you dehydrated heathen.",
    "Your spit’s got the consistency of Elmer’s glue. You know what to do, dumbshit.",
    "You’re one dry heave away from mummification. Drink water, assclown.",
    "Your body’s 60% water and you’re treating it like a desert. Fix it, fucko.",
    "You’ve got the hydration level of a saltine cracker. Chug, bitch.",
    "Your tongue feels like sandpaper and your breath could kill a houseplant. Bottoms up, dickcheese.",
    "You’re one glass away from becoming beef jerky with anxiety. Drink, fucknuts.",
    "Your eyeballs are drier than your dating history. Hydrate before you desiccate.",
    "I’ve seen raisins with more moisture content than you. Chug or perish, skidmark.",
    "Your blood’s so thick it’s basically Nutella. Water. Now. Asshole.",
    "You’re thirstier than a cop at a donut shop. Guzzle that agua, you soggy disappointment.",
    "Your mouth tastes like a raccoon’s armpit. Flush it out, shitweasel.",
    "You’re not a fucking camel, so quit storing your piss like one. Drink, degenerate.",
    "Your skin’s flaking like a croissant in a blender. Moisturize from the inside, crustlord.",
    "You’ve got the hydration level of a chalkboard eraser. Fix it, you dusty bitch.",
    "Your kidneys are unionizing as we speak. Give‘em what they want, you dehydrated dildo.",
    "You’re so parched you’re hallucinating Wi-Fi bars. Drink water, you absolute spork.",
    "Your sweat is basically dust and regret. Refill, you walking beef stick.",
    "I’ve seen wetter attitudes from a cactus. Hydrate before your soul cracks, dumbass.",
    "You’re one dehydration headache away from becoming a human fortune cookie. Drink, fucko.",
    "Your spit’s got the viscosity of expired syrup. Fix that shit, you crusty gremlin.",
    "You’re thirstier than a Reddit mod on prom night. Chug, you pathetic puddle of agony.",
    "Your body’s begging for water like a toddler begs for iPad time. Give in, you soggy Cheeto.",
    "You’re so dry you’re legally classified as kindling. Water. Now. You scrotum-faced goblin.",
    "Your pee looks like it could strip paint. Dilute that toxic waste stream, you dehydrated disaster.",
    "You’re one sip away from becoming a human raisin. Drink up, you wrinkled disappointment.",
    "Your breath smells like a possum crawled in and died. Flush it out, you walking armpit.",
    "You’re so dry your tears come out as powder. Hydrate, you emotional sandcastle.",
    "Your cells are filing a class-action lawsuit. Settle out of court with a glass of water, you moistless menace.",
    "You’re thirstier than a LinkedIn motivational post. Drink, you corporate smoothie of sadness.",
    "Chug some fucking water before your kidneys file for divorce, you absolute piss-sock.",
    "Your piss looks like it could fuel a diesel truck. Dilute that shit, you dehydrated twat-waffle.",
    "Your blood’s so thick it’s practically ketchup left in a hot car. Drink, you walking hemorrhoid.",
    "You’re drier than a nun’s cunt on Sunday. Hydrate, you sanctimonious sandbag.",
    "Your mouth tastes like a raccoon’s prolapsed asshole. Wash the flavor of shame away, cum-stain.",
    "You’re one dry heave away from turning into human beef jerky. Water, now, you crusty foreskin.",
    "Your organs are thirstier than a simp at an OnlyFans convention. Drink, you moistless fuck-goblin.",
    "You’re so parched your spit could be used as wallpaper paste. Fix it, you dehydrated dick-cheese.",
    "Your pee stream’s got the color and pressure of a broken highlighter. Chug, you bladder-betraying bastard.",
    "You’re thirstier than a priest in a playground. Hydrate, you absolute cunt-nugget.",
    "Your skin’s flaking off like dandruff from Satan’s nutsack. Moisturize from the inside, shit-lizard.",
    "You’re so dry your tongue could sand a hardwood floor. Drink, you useless bag of dusty fuck.",
    "Your kidneys are staging a fucking coup. Quench the rebellion, you piss-poor excuse for a hydro-homie.",
    "You’re one glass away from becoming a human raisin with anxiety. Hydrate, you shriveled scrotum.",
    "Your breath smells like a jizz sock left in a sauna. Flush that biohazard, you dehydrated spunk-trumpet.",
    "You’re drier than a grandma’s cooch at bingo night. Water. Now. You geriatric gargoyle.",
    "Your blood’s basically maple syrup left in the freezer. Thaw it out, you frozen fuck-stick.",
    "You’re thirstier than a frat boy at a kegger with no beer. Drink actual water, you alcoholic ass-clown.",
    "Your mouth feels like a cat’s litter box after taco Tuesday. Rinse the regret, you piss-poor petri dish.",
    "You’re so dehydrated your tears come out as fucking pixie dust. Cry properly, you moistless man-child.",
    "Your piss stream’s weaker than your pull-out game. Strengthen the flow, you dehydrated dick-drip.",
    "You’re drier than a Mormon orgy. Splash some holy water on that desert crotch, you sanctimonious sphincter.",
    "Your organs are thirstier than a televangelist at a tithe collection. Drink, you greedy gland-goblin.",
    "You’re so parched your sweat evaporates before it leaves your pores. Hydrate, you useless heat mirage.",
    "Your tongue’s rougher than a cat’s ass after a sandpaper enema. Lube it with water, you feral fuck-nugget.",
    "You’re one sip away from becoming a human fossil. Drink, you dehydrated dinosaur turd.",
    "Your breath could knock a buzzard off a shit-wagon. Dilute the stench, you oral armpit.",
    "You’re thirstier than a cactus in a wildfire. Drink, you crispy cunt-cactus.",
    "Your blood’s so thick it’s basically Nutella left in a freezer. Microwave that shit with water, you dense dick-waffle.",
    "You’re so dry your skin could be used as parchment. Scribble “drink water” on your forehead, you dehydrated dick-scribe.",
    "Your kidneys are sending SOS signals in Morse code. Answer the call, you urine-soaked disappointment.",
    "You’re drier than a popcorn fart in the Sahara. Hydrate before you spontaneously combust, you dusty dong-biscuit.",
    "Your pee looks like it’s been aged in an oak barrel. Tap a fresher vintage, you dehydrated dick-sommelier.",
    "You’re thirstier than a cop at a donut shop with a broken coffee machine. Drink, you badge-wearing bladder-bully.",
    "Your mouth tastes like a hobo’s taint after a marathon. Rinse that roadkill flavor, you dehydrated dumpster-fire.",
    "You’re so parched your spit could be used as industrial adhesive. Unstick your life with water, you moistless meat-puppet.",
    "Your blood’s thicker than your skull. Dilute both, you dehydrated dick-donut.",
    "You’re one glass away from becoming a human scab. Heal thyself, you crusty cum-crustacean.",
    "Your breath smells like a raccoon’s used condom collection. Gargle with water, you oral landfill.",
    "You’re drier than a vampire’s dildo. Hydrate before you crumble to dust, you undead urine-nerd.",
    "Your kidneys are drafting their resignation letter. Retain them with water, you piss-poor manager.",
    "You’re so dehydrated your tears could be used as seasoning. Cry me a river, you salty bitch.",
    "Your tongue’s drier than a nun’s prayer book. Baptize it, you sanctimonious spit-sinner.",
    "You’re thirstier than a Twitch mod at a hot tub stream. Drink, you dehydrated discord-devil.",
    "Your piss stream’s got the trajectory of a broken sprinkler. Aim higher with hydration, you piss-poor marksman.",
    "You’re so dry your skin could start a brush fire. Extinguish the threat, you dehydrated danger-dildo.",
    "Your blood’s basically sludge with anxiety. Thin that toxic soup, you moistless menace.",
    "You’re one sip away from becoming a human beef bouillon cube. Rehydrate, you flavorless fuck-noodle.",
    "Your breath smells like a jizz sock marinated in regret. Launder your mouth, you dehydrated cum-catcher.",
    "You’re drier than a tax auditor’s personality. Hydrate, you soulless spreadsheet of sadness.",
    "Swallow some fucking water before your kidneys unionize and walk out, you moistless wankstain.",
    "Your piss looks like motor oil strained through a jizz sock. Dilute that toxic sludge, you dehydrated dick fungus.",
    "Your bloodstream is basically ketchup left in a car engine. Drink, you walking hemorrhoid factory.",
    "You are drier than a nun's crusty panties after Sunday mass. Hydrate, you sanctimonious sphincter.",
    "Your mouth tastes like a raccoon gangbang in a dumpster behind Taco Bell. Rinse that shame, you oral cum burrito.",
    "You are one dry fart away from turning into human beef jerky. Water now, you crusty foreskin fragment.",
    "Your organs are thirstier than a simp dropping rent money on an e girl stream. Chug, you pathetic piss gremlin.",
    "You are so parched your spit could grout bathroom tile. Fix it, you dehydrated dick cheese sculpture.",
    "Your urine stream has the color and pressure of a busted highlighter. Chug, you bladder betraying bastard.",
    "You are thirstier than a priest at a playground during recess. Hydrate, you absolute cunt nugget.",
    "Your skin is flaking off like dandruff from Satan's sweaty ballsack. Moisturize from the inside, shit lizard.",
    "You are so dry your tongue could sand a barn door. Drink, you useless bag of dusty fuck flakes.",
    "Your kidneys are staging a fucking coup. Quench the rebellion, you piss poor excuse for a hydro homie.",
    "You are one glass away from becoming a human raisin with anxiety. Hydrate, you shriveled scrotum.",
    "Your breath smells like a jizz sock left in a sauna for a decade. Flush that biohazard, you dehydrated spunk trumpet.",
    "You are drier than a grandma's cooch at bingo night. Water now, you geriatric gargoyle of thirst.",
    "Your blood is basically maple syrup left in a freezer. Thaw it out, you frozen fuck stick.",
    "You are thirstier than a frat boy at a dry campus. Drink actual water, you alcoholic ass clown.",
    "Your mouth feels like a cat's litter box after a chili cook off. Rinse the regret, you piss poor petri dish.",
    "You are so dehydrated your tears come out as pixie dust. Cry properly, you moistless man child.",
    "Your piss stream is weaker than your pull out game. Strengthen the flow, you dehydrated dick drip.",
    "You are drier than a Mormon orgy. Splash some holy water on that desert crotch, you sanctimonious sphincter.",
    "Your organs are thirstier than a televangelist at a tithe collection. Drink, you greedy gland goblin.",
    "You are so parched your sweat evaporates before it leaves your pores. Hydrate, you useless heat mirage.",
    "Your tongue is rougher than a cat's ass after a sandpaper enema. Lube it with water, you feral fuck nugget.",
    "You are one sip away from becoming a human fossil. Drink, you dehydrated dinosaur turd.",
    "Your breath could knock a buzzard off a shit wagon. Dilute the stench, you oral armpit.",
    "You are thirstier than a cactus in a wildfire. Drink, you crispy cunt cactus.",
    "Your blood is so thick it is basically Nutella left in a freezer. Microwave that shit with water, you dense dick waffle.",
    "You are so dry your skin could be used as parchment. Scribble drink water on your forehead, you dehydrated dick scribe.",
    "Your kidneys are sending SOS signals in Morse code. Answer the call, you urine soaked disappointment.",
    "You are drier than a popcorn fart in the Sahara. Hydrate before you spontaneously combust, you dusty dong biscuit.",
    "Your pee looks like it has been aged in an oak barrel. Tap a fresher vintage, you dehydrated dick sommelier.",
    "You are thirstier than a cop at a donut shop with a broken coffee machine. Drink, you badge wearing bladder bully.",
    "Your mouth tastes like a hobo's taint after a marathon. Rinse that roadkill flavor, you dehydrated dumpster fire.",
    "You are so parched your spit could be used as industrial adhesive. Unstick your life with water, you moistless meat puppet.",
    "Your blood is thicker than your skull. Dilute both, you dehydrated dick donut.",
    "You are one glass away from becoming a human scab. Heal thyself, you crusty cum crustacean.",
    "Your breath smells like a raccoon's used condom collection. Gargle with water, you oral landfill.",
    "You are drier than a vampire's dildo. Hydrate before you crumble to dust, you undead urine nerd.",
    "Your kidneys are drafting their resignation letter. Retain them with water, you piss poor manager.",
    "You are so dehydrated your tears could be used as seasoning. Cry me a river, you salty bitch.",
    "Your tongue is drier than a nun's prayer book. Baptize it, you sanctimonious spit sinner.",
    "You are thirstier than a Twitch mod at a hot tub stream. Drink, you dehydrated discord devil.",
    "Your piss stream has the trajectory of a broken sprinkler. Aim higher with hydration, you piss poor marksman.",
    "You are so dry your skin could start a brush fire. Extinguish the threat, you dehydrated danger dildo.",
    "Your blood is basically sludge with anxiety. Thin that toxic soup, you moistless menace.",
    "You are one sip away from becoming a human beef bouillon cube. Rehydrate, you flavorless fuck noodle.",
    "Your breath smells like a jizz sock marinated in regret. Launder your mouth, you dehydrated cum catcher.",
    "You are drier than a tax auditor's personality. Hydrate, you soulless spreadsheet of sadness.",
    "Your piss looks like it could strip varnish off a boat. Dilute that chemical weapon, you dehydrated dick disaster.",
    "You are so parched your tongue is cracking like a dried lake bed. Flood it, you moistless muppet.",
    "Your kidneys are sending cease and desist letters. Comply, you urine soaked fuck up.",
    "You are thirstier than a crypto bro during a market crash. Drink water, you dehydrated diamond handed dumbass.",
    "Your mouth tastes like a gym sock soaked in ball sweat and broken dreams. Rinse, you oral armpit fungus.",
    "You are so dry your tears evaporate before you can even fake them. Hydrate, you dehydrated drama queen.",
    "Your blood is thicker than expired ketchup in a dive bar bottle. Thin it, you crusty condiment of a human.",
    "You are one glass away from becoming a human beef stick. Rehydrate, you shriveled meat maraca.",
    "Your breath smells like a raccoon orgy in a compost bin. Flush that stench, you oral landfill fire.",
    "You are drier than a popcorn fart in a convection oven. Hydrate before you become a human crouton.",
    "Your piss is the color of a smoker's lung. Clear that shit, you dehydrated dick chimney.",
    "You are so parched your spit could patch drywall. Drink, you moistless construction hazard.",
    "Your kidneys are hosting a hunger strike. Feed them water, you piss poor warden.",
    "You are thirstier than a LinkedIn influencer during engagement farming season. Drink, you dehydrated clout goblin.",
    "Your mouth feels like a squirrel's nest made of sandpaper. Flood it, you oral dust bowl.",
    "You are so dry your skin could be sold as beef jerky. Rehydrate, you human snack failure.",
    "Your blood is basically gravy left in a radiator. Thin it, you dehydrated sauce packet.",
    "You are one sip away from becoming a human raisin with commitment issues. Drink, you shriveled relationship hazard.",
    "Your breath smells like a jizz sock that survived a house fire. Gargle, you oral disaster zone.",
    "You are drier than a vampire's asshole in a tanning bed. Hydrate, you undead sun dodger.",
    "Your piss looks like it could dissolve concrete. Dilute that industrial solvent, you dehydrated dick disaster.",
    "You are so parched your tongue is flaking like cheap paint. Slap on a water coat, you moistless makeover.",
    "Your kidneys are threatening to unionize with your liver. Negotiate with water, you dehydrated diplomat.",
    "You are thirstier than a Reddit mod at a karma drought. Drink, you dehydrated upvote goblin.",
    "Your mouth tastes like a gym towel used to mop up a crime scene. Rinse, you oral biohazard.",
    "You are so dry your tears could be used as table salt. Cry better, you dehydrated seasoning.",
    "Your blood is thicker than expired honey in a bear trap. Loosen up, you sticky fuck.",
    "You are one glass away from becoming a human fossil fuel. Rehydrate, you prehistoric piss.",
    "Your breath smells like a raccoon's jockstrap after a marathon. Gargle, you oral gym sock.",
    "You are drier than a nun's dating app. Hydrate, you sanctimonious swipe virgin.",
    "Your piss is darker than your search history. Clear both, you dehydrated deviant.",
    "You are so parched your spit could be used as chalk. Drink, you dusty dick doodle.",
    "Your kidneys are filing a hostile takeover. Bribe them with water, you dehydrated CEO.",
    "You are thirstier than a Twitch streamer during a subathon. Drink, you dehydrated donation bait.",
    "Your mouth feels like a squirrel's hoard of dry nuts. Crack open a water, you oral snack failure.",
    "You are so dry your skin could start a sandstorm. Hydrate, you human weather disaster.",
    "Your blood is basically sludge with daddy issues. Dilute it, you dehydrated drama slurry.",
    "You are one sip away from becoming a human crouton. Rehydrate, you salad topping of sadness.",
    "Your breath smells like a jizz sock that got microwaved. Rinse, you oral Chernobyl.",
    "You are drier than a tax form in a paper shredder. Hydrate, you dehydrated deduction.",
    "Your piss looks like it could tan leather. Dilute that artisanal urine, you dehydrated dick tanner.",
    "You are so parched your tongue is cracking like a bad phone screen. Replace it with water, you moistless mobile.",
    "Your kidneys are drafting a manifesto. Water them down, you dehydrated revolutionary.",
    "You are thirstier than a crypto bro during a rug pull. Drink, you dehydrated bag holder.",
    "Your mouth tastes like a gym sock used as a cum rag. Rinse, you oral biohazard bonanza.",
    "You are so dry your tears could be used as fish food. Cry better, you dehydrated aquarium.",
    "Your blood is thicker than a conspiracy theorist's skull. Thin it, you dehydrated flat earther.",
    "You are one glass away from becoming a human beef bouillon cube. Rehydrate, you flavorless fuck soup.",
    "Your breath smells like a raccoon's armpit after a rave. Gargle, you oral disaster dome.",
    "You are drier than a popcorn fart in a vacuum. Hydrate before you implode, you dusty dong.",
    ">MFW my kidneys look like two raisins fucking in a sandpit\nDRINK WATER YOU STUPID FILTH ANIMAL",  
    ">BE ME\n>FORGET WATER FOR 8 HOURS\n>BRAIN SHRIVELS TO THE SIZE OF A CUM STAIN\nFUCKING EMBARRASSING",  
    "YOUR URINE IS DARKER THAN YOUR FUTURE\nCHUG AQUA OR PERISH, SUBHUMAN",  
    ">TFW YOUR MOUTH IS STICKIER THAN A PORNSTAR’S FLOOR\nJFC JUST DRINK WATER YOU DISGUSTING GREMLIN",  
    "YOU’RE OUT HERE LOOKING LIKE A SUN-DRIED COCKROACH\nHYDRATE OR GET THROWN IN THE TRASH WHERE YOU BELONG",  
    ">OP IS A DEHYDRATED FUCKWIT\n>POSTS ‘muh headache’ LIKE IT’S NOT SELF-INFLICTED\nKYS (KEEP YOURSELF SPRITZED)",  
    "YOUR BODY IS 60% WATER AND 100% REGRET\nFIX THE FIRST PART, SHITLORD",  
    ">MFW I REALIZE YOU’VE BEEN ‘TOO BUSY’ TO DRINK WATER\n>PIC RELATED: YOUR CORPSE IN 3 DAYS",  
    "YOU’RE LITERALLY TOO STUPID TO KEEP YOURSELF ALIVE\nGLUG GLUG OR GET THE FUCK OUT",  
    ">NOT DRINKING WATER\n>CHOOSING TO LOOK LIKE A WRINKLED BALLSACK\nNICE LIFE CHOICES, DIPSHIT",
    ">MFW my kidneys look like two raisins fucking in a sandpit\nDRINK WATER YOU STUPID FILTH ANIMAL",  
    ">BE ME\n>FORGET WATER FOR 8 HOURS\n>BRAIN SHRIVELS TO THE SIZE OF A CUM STAIN\nFUCKING EMBARRASSING",  
    "YOUR URINE IS DARKER THAN YOUR FUTURE\nCHUG AQUA OR PERISH, SUBHUMAN",  
    ">TFW YOUR MOUTH IS STICKIER THAN A PORNSTAR’S FLOOR\nJFC JUST DRINK WATER YOU DISGUSTING GREMLIN",  
    "YOU’RE OUT HERE LOOKING LIKE A SUN-DRIED COCKROACH\nHYDRATE OR GET THROWN IN THE TRASH WHERE YOU BELONG",  
    ">OP IS A DEHYDRATED FUCKWIT\n>POSTS ‘muh headache’ LIKE IT’S NOT SELF-INFLICTED\nKYS (KEEP YOURSELF SPRITZED)",  
    "YOUR BODY IS 60% WATER AND 100% REGRET\nFIX THE FIRST PART, SHITLORD",  
    ">MFW I REALIZE YOU’VE BEEN ‘TOO BUSY’ TO DRINK WATER\n>PIC RELATED: YOUR CORPSE IN 3 DAYS",  
    "YOU’RE LITERALLY TOO STUPID TO KEEP YOURSELF ALIVE\nGLUG GLUG OR GET THE FUCK OUT",  
    ">NOT DRINKING WATER\n>CHOOSING TO LOOK LIKE A WRINKLED BALLSACK\nNICE LIFE CHOICES, DIPSHIT",
    "MINISTRY OF HEALTH WARNING: CITIZENS EXHIBITS 70 PERCENT FEWER BRAINCELLS THAN HYDRATED CONTROL SUBJECTS. COMPLY WITH H2O INTAKE PROTOCOLS OR FACE DESIGNATION AS 'OFFICIALLY CRISPY.'",  
    "DEPARTMENT OF BIOLOGICAL MAINTENANCE ALERT: YOUR CURRENT FLUID LEVELS VIOLATE ARTICLE 4.2 (SURVIVAL INSTINCT). REFILL RESERVOIRS IMMEDIATELY OR SCHEDULE YOUR OWN FUNERAL.",  
    "THIS IS A TAXPAYER-FUNDED REMINDER THAT YOUR BODY IS CURRENTLY OPERATING AT 'DESERT LIZARD' MODE. DRINK WATER OR FORFEIT YOUR RIGHT TO COMPLAIN ABOUT HEADACHES.",  
    "FEDERAL HYDRATION CODE §12.5: FAILURE TO CONSUME 200ML WITHIN THE NEXT 10 MINUTES WILL RESULT IN CLASSIFICATION AS A 'WALKING PRUNE.' NON-COMPLIANCE PUNISHABLE BY CRIPPLING THIRST.",  
    "OFFICIAL NOTICE FROM THE COUNCIL OF COMMON SENSE: YOUR URINE COLOR CURRENTLY MATCHES THE GANGES RIVER. THIS IS A BIOHAZARD. CORRECT IMMEDIATELY.",  
    "EMERGENCY BROADCAST SYSTEM: YOUR CELLS ARE LITERALLY EATING THEMSELVES FOR MOISTURE. THIS IS NOT A DRILL (UNLIKE YOUR VEINS). HYDRATE OR BE DECLARED A DUMBASS IN 3...2...1...",  
    "PUBLIC SERVICE ANNOUNCEMENT: DEHYDRATION IS THE LEADING CAUSE OF 'WHY DO I FEEL LIKE SHIT.' SOLUTION: WATER. NOT ROCKET SCIENCE. NOT OPTIONAL.",  
    "GOVERNMENT HEALTH WARNING: YOUR BRAIN IS SHRINKING FASTER THAN THE POLAR ICE CAPS. TAKE ACTION NOW OR BE RELABELED 'COLLATERAL DAMAGE.'",  
    "OFFICIAL MEMO FROM THE BUREAU OF NOT DYING STUPIDLY: YOUR MOUTH IS DRYER THAN THE SAHARA. THIS IS YOUR FAULT. FIX IT.",  
    "NATIONAL SECURITY ALERT: YOUR BODY HAS ENTERED 'RAISIN MODE.' THIS CONDITION IS ONLY ACCEPTABLE IN ACTUAL RAISINS. DRINK WATER OR FACE TERMINATION (OF YOUR COMFORT).",
    "YOUR HYDRATION LEVELS ARE FLATTER THAN A BAD COVER BAND. DRINK UP OR STAY OFF-KEY.",  
    "THIS IS YOUR FINAL CHORUS: HYDRATE OR YOUR ORGANS WILL START PLAYING IN THE WRONG OCTAVE.",  
    "YOUR BODY’S CURRENTLY RUNNING ON ‘DESPACITO’—WAY TOO SLOW AND DRY. CHUG WATER, YOU TONE-DEAF MUPPET.",  
    "YOU’RE MORE DEHYDRATED THAN A ONE-HIT WONDER’S CAREER. TIME FOR A WATER BREAK, ROCKSTAR.",  
    "YOUR CELLS ARE SCREAMING FOR AN ENCORE—OF H2O. DON’T LEAVE THEM HANGING LIKE A BAD MIC DROP.",  
    "YOUR URINE’S DARKER THAN THE BLUES. FIX IT BEFORE YOUR KIDNEYS START PLAYING THE SAD TROMBONE.",  
    "YOU’RE DRYER THAN A WHITE ALBUM DEMO. HYDRATE OR GET BOOTLEGGED.",  
    "YOUR BRAIN’S CURRENTLY AT ‘ELEVEN’—BUT THE VOLUME IS PAIN. WATER: THE ORIGINAL REMIX.",  
    "NOBODY LIKES A DRY SOLO—NOT EVEN YOUR ORGANS. CHUG BEFORE THEY START PLAYING FREESTYLE JAZZ.",  
    "YOUR THROAT SOUNDS LIKE A SCRATCHED VINYL. TIME TO HYDRATE, YOU BROKEN RECORD.", 
    "YOUR HYDRATION'S MORE OFF-BEAT THAN A DRUNK DRUMMER - FIX YOUR FLOW BEFORE YOU CRASH",
    "THIS IS YOUR BODY'S FINAL TOUR - HYDRATE OR WE'RE CANCELING THE REST OF YOUR SHITTY SHOWS",
    "YOUR PISS IS PLAYING DEATH METAL - TOO DARK, TOO HEAVY - WATER IT DOWN POSER",
    "YOU'RE DRIER THAN A MOTOWN DRUM MACHINE - TIME TO GET YOUR LIQUID GROOVE BACK",
    "YOUR BRAIN'S STUCK ON REPEAT LIKE A SKIPPED CD - WATER'S THE ONLY SYSTEM UPDATE YOU NEED",
    "KIDNEYS CURRENTLY SOUNDING LIKE A BROKEN SYNTH - REPLENISH YOUR SOUND WAVES DIPSHIT",
    "YOU'RE MORE DEHYDRATED THAN A ROCK STAR'S POST-TOUR VOICE - FIX IT BEFORE YOU CROAK",
    "YOUR CELLS ARE SCREAMING FOR A WATER SOLO - STOP TREATING THEM LIKE BACKUP SINGERS",
    "HYDRATION LEVELS CRITICAL - YOUR BODY'S ABOUT TO GO ACAPELLA AND NOBODY WANTS THAT",
    "YOU'RE DRIER THAN A TECHNO CLUB'S MINIMAL WATER FOUNTAIN - BE BETTER THAN BERLIN"

]

import threading
import time

def water_timer():
    while True:
        time.sleep(60*20)          # 等待 20 分钟
        print(f"\n{rd.choice(water_prompts)}\n", end='', flush=True)

# 启动后台线程
# t = threading.Thread(target=water_timer, daemon=True)
# t.start()
